### PR TITLE
Home button. Fix #47

### LINKED ISSUE #47: Back button, logo or Home link do not get me to the main page.
Back button, logo or Home link do not get me to the main page.

Steps to reproduce:
1. go to the the main page: https://www.opensuse.org/
2. select leap or tumbleweed.
3. click Back button, logo or Home link 

Actual behavior: nothing happens, you remain on the same page with leap or tumble weed selected.
Expected behavior: i am taken to the page where i can again select leap or tumbleweed.

Note: a link "back to main page" works perfectly. I expect back, home and logo link to work the same

### PR DESCRIPTION
**Pull request by bisht-richa**

### CODE REVIEW

File: assets/js/opensuse-theme.js [hunk 1]
```diff
@@ -186,6 +186,17 @@ function osMoreInformation(os) {
     $('.back-to-main-page').on('click', function() {
       backToMainPageOs($osSelected)
     })
+    
+    $('#home, #opensuseLogo').on('click', function() {
+        scrolled = $(window).scrollTop();
```
Comment (cyntss) [inline assets/js/opensuse-theme.js]: can you check your indentation here ? It looks like you are using more than 2 spaces and we really want to have a clean indentation in all documents :)

File: assets/js/opensuse-theme.js [hunk 2]
```diff
@@ -431,3 +433,14 @@ window.fbAsyncInit = function() {
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
 
+
+
+window.onkeyup = function(e) {
+   var key = e.keyCode ? e.keyCode : e.which;
+
+   if (key == 8) {
```
Comment (cyntss) [inline assets/js/opensuse-theme.js]: Can you add the ESC key here as well? That would be really good and intuitive as well 👍

File: assets/js/opensuse-theme.js [hunk 3]
```diff
@@ -133,8 +133,9 @@ function osMoreInformation(os) {
 
   moreInfoOpened = true
   //get the height of the main container
-  containerHeight = $('#opensuse-os').outerHeight()
-
+  containerHeight = $('#opensuse-os').outerHeight();
+  window.location.hash = '0';
```
Comment (cyntss) [inline assets/js/opensuse-theme.js]: I dont really like this solution because it adds a hashtag #0 in the URL, which means nothing at all for a user.

I was gonna propose to add it as:

window.location.hash = title; (where titles is the name of the OS selected), so then the URL would change to: 

http://localhost:8000/#Leap

or 

http://localhost:8000/#Tumbleweed

And I like it more, but not 100%. 
If we decide to go in that direction, what I would recommend then, is that we detect when the URL has a hash, and if it does, then we automatically open the OS info with:

osMoreInformation(HashtagURL)

Otherwise, lets just detect the keydown and if it is backspace then we close the information.

@bisht-richa You decide how to go for now. If you prefer to go for detecting the event on keydown, then I can open a new Issue with that idea that just came up to have URL for users to share.

File: assets/js/opensuse-theme.js [hunk 4]
```diff
@@ -186,6 +187,18 @@ function osMoreInformation(os) {
     $('.back-to-main-page').on('click', function() {
       backToMainPageOs($osSelected)
     })
+    
+    $('#home, #opensuseLogo').on('click', function() {
+        scrolled = $(window).scrollTop();
+        if (scrolled > mainSectionHeight) {
+            setTimeout('backToMainPageOs($osSelected)', 900);
```
Comment (cyntss) [inline assets/js/opensuse-theme.js]: I like this solution with the timeout 👍

File: assets/js/opensuse-theme.js [hunk 5]
```diff
@@ -420,3 +433,14 @@ window.fbAsyncInit = function() {
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
 
+
+
+window.onkeyup = function(e) {
+   var key = e.keyCode ? e.keyCode : e.which;
```
Comment (cyntss) [inline assets/js/opensuse-theme.js]: Check the indentation here as well  :)  (only 2 spaces)

**Comment by cyntss** [comment]
@bisht-richa Please before you start working on this tomorrow, make a "git pull rebase", because I added a commit in the branch, declaring some variables that were not declared before.

If you have any conflict while pulling the data, please let me know so I can help you out.

File: assets/js/opensuse-theme.js (hunk 3 above)
Comment (bisht-richa) [inline assets/js/opensuse-theme.js]: I am adding hashtag, because in Chrome when you hit Backspace button it navigate you to previous page.

Comment (cyntss) [inline assets/js/opensuse-theme.js]: That was completely understood. My point was to make it even better by having an actual URL. But its fine, I will create a new card for that to work on it this friday ;)

**Comment by cyntss** [comment]
There is one little thing I would add:

When I open "LEAP" (for example) in the URL I will see "/#Leap", then I click on the backspace button on my keyboard, and the "/#Leap" will be removed. That is the perfect state.
But. If I open "LEAP", then I see "/#Leap" in the URL, and then I press on Home or the openSUSE Logo, but the URL is not cleared up.

So, I would request that last change, that pressing on HOME or the LOGO it removed the #NAME from the URL.

**Comment by cyntss** [comment]
another comment.

You have the commit: 

Added escape button code and titile to hash tag

and

Added escape button code and titile to hash tag - main min 

They are the same change, but you forgot to put the minified file inside the first commit. 
For the next commits, remember to put all the files associated to one change, inside 1 commit only 👍
